# 地图路径
MapFile_address: "../../PoseData/map1.pgm"
# 初始化原点路径                                
OriginFile_address: "../../PoseData/OriginPose/OriginPose1.txt"
# 轨迹路径
TrajectoryFile_address: "../../PoseData/Trajectory/2024-03-26 08_48_46.txt"

radius: 0.4           # 热力图搜索半径
TPointSize: 20        # 轨迹点的大小
MapPointSize: 20      # 地图点的大小
origin_x: -15.093980  # 地图的原点偏移，在map.yaml
origin_y: -28.889954  # 地图的原点偏移，在map.yaml
resolution: 0.050000  # 地图分辨率，在map.yaml
OffSetByHand_x: 0     # 手动偏移x
OffSetByHand_y: 50    # 手动偏移y

# 输出的文件名，默认路径为drawing目录下
OutputFileName: trajectory